### ISSUE TITLE
"Latest version" link leads to penultimate version.

### ISSUE THREAD

**Issue by Juerd** [CPAN-API/metacpan-web#1451] opened 2015-02-05 21:46 UTC
https://metacpan.org/pod/Net::MQTT::Simple gets you version 1.16, while 1.20 was released today. The new version, 1.20, is available in the Jump to version box.

**Comment by haarg** [comment] 2015-02-05 22:15
This is most likely a browser caching issue.  The link posted goes to 1.20 for me.

**Comment by mjemmeson** [comment] 2015-02-17 09:20
Happens with other modules - get a 304 Not Modified, yet date in "If-Modified-Since" predates latest version

**Comment by ranguard** [comment] 2016-03-08 20:45
Dupe of #1522

**Closed by ranguard** 2016-03-08 20:45 UTC
