### ISSUE TITLE
Metacpan randomly 404s

### ISSUE THREAD

**Issue by dgl** [CPAN-API/metacpan-web#1423] opened 2014-11-20 01:36 UTC
Take the following search as an example:
http://grep.cpan.me/?q=%28^|[^%23]%29\buse\s%2Bencoding\s+-file%3AChange%28s|log%29|.*\.%28t|pod%29|encoding\.pm

cpangrep assumes that the source code can be found at:

   "https://metacpan.org/source/$author/$filename";

[Where $filename is basically what Cpan::DistnameInfo calls the dist plus the local part of the filename.]

It links to the relevant deep URL. Such as https://metacpan.org/source/MORAGO/downsexta-0.2-2/downsexta/DataSexta.pm#L1

I think metacpan is broken, sometimes I get this (per Chrome debug tools):

Remote Address:23.235.37.143:443
Request URL:https://metacpan.org/source/MORAGO/downsexta-0.2-2/downsexta/DataSexta.pm
Request Method:GET
Status Code:404 Not Found

Yet sometimes it works:

Remote Address:23.235.37.143:443
Request URL:https://metacpan.org/source/MORAGO/downsexta-0.2-2/downsexta/DataSexta.pm
Request Method:GET
Status Code:200 OK

**Comment by ranguard** [comment] 2015-03-23 20:32
Dupe of cpan-api #259 issue - closing

**Closed by ranguard** 2015-03-23 20:32 UTC
