### ISSUE TITLE
Extra anchors for perldoc

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1441] opened 2015-01-15 12:39 UTC
On https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod the only anchor for the ```accept``` function is this:
https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod#accept-NEWSOCKET-GENERICSOCKET

I think it would be better if https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod#accept
also worked.

**Comment by haarg** [comment] 2015-09-16 14:44
Duplicate of #1241

**Closed by haarg** 2015-09-16 14:44 UTC
Labels: Volunteer needed
