### ISSUE TITLE
Why is the same module listed three times at metacpan.org?

### ISSUE THREAD

**Issue by hakonhagland** [CPAN-API/metacpan-web#1557] opened 2015-07-12 20:13 UTC
Searching for `Devel::Peek` at metacpan.org gives the  following screen shot:

![devel](https://cloud.githubusercontent.com/assets/6708379/8639731/c4e0afae-28e2-11e5-95cc-e9c7f2362fe3.png)

Why is the module listed three times? (It looks a little bit strange, and could easily confuse the user..)

Note: this issue was first asked as a question on stackoverflow.com. Here is the [link](http://stackoverflow.com/questions/31368725/why-is-the-same-module-listed-three-times-at-metacpan-org) which have an answer with some more information..

**Comment by ikegami** [comment] 2015-07-12 20:40
Worse, the official distribution isn't one of the three shown!

**Comment by ranguard** [comment] 2016-03-04 22:23
Dupe of #1231

**Closed by ranguard** 2016-03-04 22:23 UTC
