### ISSUE TITLE
Link to Changes even when a distro has no Changes

### ISSUE THREAD

**Issue by andk** [CPAN-API/metacpan-web#1433] opened 2015-01-06 07:23 UTC
https://metacpan.org/release/SREZIC/Acme-PM-Berlin-Meetings-201501.05

This distro has no Changes file but the menu to the left shows a Changes link. Is there a rationale? I think I'd prefer that the link goes away when there is nothing to link to.

Cheers,

**Comment by haarg** [comment] 2015-01-06 11:27
At the point that the link is created, the page doesn't know if the Changes file exists or not.  Doing this properly involves API support.

Dupe of #1107

**Closed by haarg** 2015-01-06 11:27 UTC
