### ISSUE TITLE
"Testers" stats in side-bar for dev releases is incorrect

### ISSUE THREAD

**Issue by timbunce** [CPAN-API/metacpan-web#1401] opened 2014-10-24 10:48 UTC
The side-bar for https://metacpan.org/pod/release/TIMB/DBI-1.631_90-TRIAL/DBI.pm shows "Testers (2404 / 34 / 41)" but both the links (to www.cpantesters.org and matrix.cpantesters.org) show no errors.

The side-bar for the previous full release http://matrix.cpantesters.org/?dist=DBI+1.631 shows the same figures. So it seems they're being reused in error for the later trial release.

**Comment by pwr22** [comment] 2015-01-19 15:29
I find that if I make a dev release simply using an underscored sub version that the testers stuff is displayed as [normal]{https://metacpan.org/pod/release/PWR/CloudFlare-Client-0.03_1/lib/CloudFlare/Client.pm}

but if I made a dev release with an underscored sub version and a -TRIAL suffix that no testing info is [displayed at all]{https://metacpan.org/pod/release/PWR/CloudFlare-Client-0.03_6-TRIAL/lib/CloudFlare/Client.pm}

Though I haven't encountered this re-use issue yet. I came here to report the above and I'm wondering if it could be a common failure in the handling of dev releases?

**Comment by haarg** [comment] 2015-01-19 20:33
This is roughly the same as #886

**Comment by ranguard** [comment] 2016-03-04 22:09
Closing as partly dupe of #886

**Closed by ranguard** 2016-03-04 22:09 UTC
Labels: type:Bug
